services:
  dbtool:
    image: postgres:18
    container_name: dbtool
    restart: "no"
    environment:
      PGHOST: pgdb
      PGPORT: 5432
      PGUSER: ${POSTGRES_USER:-postgres}
      PGPASSWORD_FILE: /run/secrets/POSTGRES_PASSWORD
      # >>> App-specific variables <<<
      APP_USER: fundusAppUser4   # <-- CHANGE THIS
      APP_DB: fundusAppDb4       # <-- CHANGE THIS
      APP_SCHEMA: fundusAppSchema4   # <-- CHANGE THIS

    entrypoint: ["/bin/bash","-lc","/sql/dbtool.sh"]
    volumes:
      - ./apps/create_app.sql:/sql/create_app.sql:ro
      - ./apps/dbtool.sh:/sql/dbtool.sh:ro
    secrets:
      - POSTGRES_PASSWORD
      - APP_PASSWORD       
    networks:
      - pgnet

networks:
  pgnet:
    external: true
    name: pgnet

secrets:
  POSTGRES_PASSWORD:
    file: ./secrets/POSTGRES_PASSWORD
  APP_PASSWORD:
    file: ./secrets/fundusApp_PASSWORD4 # <-- CHANGE THIS To set / change password
