services:
  pg_basebackup_runner:
    image: postgres:18
    user: root
    container_name: pg_basebackup_runner
    restart: always
    environment:
      PGHOST: pgdb
      PGPORT: "5432"
      PGUSER: replicator
      PGPASSWORD_FILE: /run/secrets/REPL_PASSWORD
      BACKUP_DIR: /backups/full
      SCHEDULE_CRON: "0 16 * * *"    # daily at 16:00
      # RUN_ONCE: "true"             # uncomment to run once and exit
    secrets:
      - REPL_PASSWORD
    volumes:
      - ./backups:/backups
      - ./bin/pgbackup_entrypoint.sh:/usr/local/bin/pgbackup_entrypoint.sh:ro
      - ./bin/pg_do_basebackup.sh:/usr/local/bin/pg_do_basebackup.sh:ro
    networks:
      - pgnet
    entrypoint: ["/usr/local/bin/pgbackup_entrypoint.sh"]

networks:
  pgnet:
    name: pgnet
    external: true

secrets:
  REPL_PASSWORD:
    file: ./secrets/REPL_PASSWORD
